apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: preprocessor
  kubernetes:
    cluster:
      annotations:
        gke.project: sandbox-spin
        gke.location: us-central1-a  
  annotations:
    'backstage.io/kubernetes-id': preprocessor
  description: SSD Data preprocessor
  tags:
    - golang
    - data
      #links:
      #    - url: https://example.com/user
      #      title: Examples Users
      #      icon: user
      #  annotations:
      #    backstage.io/linguist: 'https://github.com/girichinna27/bs-components/tree/master/plugins/playlist'
spec:
  type: service
  lifecycle: experimental
  owner: ssd-team
  system: ssd
  dependsOn: ['resource:postgres']
  apiConsumedBy: ['component:ssd-ui']
